# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  - push
  - pull_request

jobs:
  build:
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        # Keep synchronized with setup.py and tox.ini
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}
    env:
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Install cairo on MacOS
        run: brew install cairo
        if: ${{ matrix.platform == 'macos-latest' }}
      - name: Test with pytest
        run: |
          python -m tox -e py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: PYTHON
